return {
    {
        CharacterName = "Hunter",
        Attacks = {
            {
                AttackName = "Attack 1",
                AttackDebounce = 10,
                AttackDuration = 3,
            },
            {
                AttackName = "Attack 2",
                AttackDebounce = 10,
                AttackDuration = 3,
            },
            {
                AttackName = "Attack 3",
                AttackDebounce = 10,
                AttackDuration = 3,
            },
            {
                AttackName = "Attack 4",
                AttackDebounce = 10,
                AttackDuration = 3,
            },

        },
    },
}